In [1]:
import pandas as pd

df = pd.read_csv('used_cars_data.csv')
df.shape

(7253, 14)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   object
 2   Location           7253 non-null   object
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   object
 6   Transmission       7253 non-null   object
 7   Owner_Type         7253 non-null   object
 8   Mileage            7251 non-null   object
 9   Engine             7207 non-null   object
 10  Power              7207 non-null   object
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   object
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 793.4+ KB

In [3]:
new_df = df.sample(n=50)  ## random sampling 
new_df.shape

(50, 14)

In [4]:
new_df.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='object')

In [ ]:
# drop some unwanted columns
# rename columns Kilometeres_Driven -> km
# drop duplicates
# Test with null values -> replace null values

In [6]:
new_df.drop(columns=['S.No.','New_Price','Transmission','Owner_Type','Seats'],inplace=True)

In [7]:
new_df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type', 'Mileage',
       'Engine', 'Power', 'Price'],
      dtype='object')

In [8]:
new_df.shape

(50, 9)

In [9]:
new_df.head(3)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Mileage,Engine,Power,Price
1338,Hyundai Xcent 1.2 Kappa SX,Mumbai,2016,10200,Petrol,19.1 kmpl,1197 CC,82 bhp,4.99
7075,BMW 5 Series 2013-2017 530d M Sport,Kochi,2015,58898,Diesel,14.69 kmpl,2993 CC,258 bhp,NaN
6191,Volkswagen Passat 1.8 TSI MT,Coimbatore,2011,58865,Petrol,14.3 kmpl,1798 CC,160 bhp,NaN

In [10]:
new_df.isnull().sum()

Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Mileage              0
Engine               0
Power                0
Price                4
dtype: int64

In [12]:
import numpy as np
new_df['Price'].fillna(np.mean(new_df['Price']),inplace=True)

C:\Users\karth\AppData\Local\Temp\ipykernel_27352\1476825652.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['Price'].fillna(np.mean(new_df['Price']),inplace=True)

In [13]:
new_df.isnull().sum()

Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Mileage              0
Engine               0
Power                0
Price                0
dtype: int64

In [14]:
new_df.duplicated().sum()

np.int64(0)

In [15]:
new_df.drop_duplicates(inplace=True)

In [16]:
new_df.isnull().sum()

Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Mileage              0
Engine               0
Power                0
Price                0
dtype: int64

In [17]:
new_df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type', 'Mileage',
       'Engine', 'Power', 'Price'],
      dtype='object')

In [18]:
new_df.rename(columns={'Kilometers_Driven':'KM','Fuel_Type':'Fuel'},inplace=True)

In [19]:
new_df.columns

Index(['Name', 'Location', 'Year', 'KM', 'Fuel', 'Mileage', 'Engine', 'Power',
       'Price'],
      dtype='object')

In [20]:
new_df.head(1)

,Name,Location,Year,KM,Fuel,Mileage,Engine,Power,Price
1338,Hyundai Xcent 1.2 Kappa SX,Mumbai,2016,10200,Petrol,19.1 kmpl,1197 CC,82 bhp,4.99

In [21]:
new_df.groupby('Location')['Price'].sum()

Location
Ahmedabad       8.250000
Bangalore      82.650000
Chennai         4.400000
Coimbatore     41.183043
Delhi          73.610000
Hyderabad      34.340000
Jaipur         18.670000
Kochi         105.266522
Kolkata         7.450000
Mumbai         63.306522
Pune            9.200000
Name: Price, dtype: float64

In [23]:
new_df.groupby('Location')['Price'].agg(['sum','mean'])

                   sum       mean
Location
Ahmedabad     8.250000   8.250000
Bangalore    82.650000  16.530000
Chennai       4.400000   2.200000
Coimbatore   41.183043  10.295761
Delhi        73.610000  12.268333
Hyderabad    34.340000   6.868000
Jaipur       18.670000   4.667500
Kochi       105.266522  11.696280
Kolkata       7.450000   2.483333
Mumbai       63.306522   7.913315
Pune          9.200000   3.066667

In [25]:
new_df['Price'].sort_values(ascending=False)

1028    38.750000
5242    37.900000
2470    33.660000
5460    32.000000
357     27.300000
3398    24.250000
4559    17.510000
4984    16.270000
5345    13.300000
3141    10.000000
6748     8.966522
7075     8.966522
6863     8.966522
6191     8.966522
218      8.900000
931      8.250000
2124     7.740000
3840     7.650000
1804     6.980000
1549     6.730000
3629     6.600000
3894     6.500000
1581     6.500000
2501     6.450000
1517     6.170000
951      5.830000
3110     5.340000
1338     4.990000
2535     4.790000
3250     4.700000
4472     4.500000
4881     4.400000
3932     4.350000
2419     3.900000
2495     3.750000
5619     3.650000
4908     3.530000
2427     3.500000
907      3.300000
1853     3.250000
2059     3.050000
1872     2.900000
2197     2.500000
5469     2.400000
5452     2.300000
5457     2.000000
5234     1.650000
402      0.920000
2634     0.800000
5453     0.750000
Name: Price, dtype: float64

In [31]:
new_df['Location'].sort_values(ascending=False)

5453          Pune
3840          Pune
2634          Pune
6863        Mumbai
1872        Mumbai
2495        Mumbai
1581        Mumbai
2059        Mumbai
3398        Mumbai
218         Mumbai
1338        Mumbai
2427       Kolkata
5234       Kolkata
5452       Kolkata
1549         Kochi
1517         Kochi
2124         Kochi
3110         Kochi
951          Kochi
7075         Kochi
357          Kochi
2470         Kochi
4908         Kochi
402         Jaipur
4472        Jaipur
3141        Jaipur
1853        Jaipur
3894     Hyderabad
907      Hyderabad
2535     Hyderabad
2501     Hyderabad
5345     Hyderabad
3629         Delhi
4559         Delhi
3932         Delhi
1028         Delhi
2419         Delhi
2197         Delhi
6191    Coimbatore
4984    Coimbatore
6748    Coimbatore
1804    Coimbatore
5457       Chennai
5469       Chennai
5242     Bangalore
3250     Bangalore
5619     Bangalore
4881     Bangalore
5460     Bangalore
931      Ahmedabad
Name: Location, dtype: object

In [ ]:
##############